osquickstart/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.conf.urls.static import static

from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer

WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"

urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    }, name="home"),
    url(r"^admin/", include(admin.site.urls)),
    
    url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
    url(r"^account/", include("account.urls")),
    
    url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^sponsors/", include("symposion.sponsorship.urls")),
    url(r"^boxes/", include("symposion.boxes.urls")),
    url(r"^teams/", include("symposion.teams.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^markitup/", include("markitup.urls")),
    
    url(r"^", include("symposion.cms.urls")),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

osquickstart/proposals/models.py
from django.db import models

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):
    
    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    
    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
    ]
    
    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)
    
    recording_release = models.BooleanField(
        default=True,
        help_text="By submitting your proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box."
    )
    
    class Meta:
        abstract = True


class TalkProposal(Proposal):
    class Meta:
        verbose_name = "talk proposal"


class TutorialProposal(Proposal):
    class Meta:
        verbose_name = "tutorial proposal"

osquickstart/proposals/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from .models import TalkProposal, TutorialProposal


class ProposalForm(forms.ModelForm):
    
    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

osquickstart/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}
{% load url from future %}

<div class="pull-right">
    <ul class="nav pull-right">
        {% if request.user.is_authenticated %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {% user_display request.user %}
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "dashboard" %}"><i class="icon-tasks"></i> {% trans "Dashboard" %}</a></li>
                    <li><a href="{% url "account_settings" %}"><i class="icon-user"></i> {% trans "Settings" %}</a></li>
                    {% if request.user.is_staff %}
                        <li><a href="{% url THEME_ADMIN_URL|default:"admin:index" %}"><i class="icon-cog"></i> {% trans "Admin" %}</a></li>
                    {% endif %}
                    <li class="divider"></li>
                    <li>
                        <a id="account_logout" href="{% url "account_logout" %}"><i class="icon-off"></i> {% trans "Log out" %}</a>
                    </li>
                </ul>
            </li>
        {% else %}
            <li><a href="{% url "account_login" %}">{% trans "Log in" %}</a></li>
            {% if ACCOUNT_OPEN_SIGNUP %}
                <li><a href="{% url "account_signup" %}">{% trans "Sign up" %}</a></li>
            {% endif %}
        {% endif %}
    </ul>
</div>

<form id="accountLogOutForm" style="display: none;" action="{% url "account_logout" %}" method="POST">
    {% csrf_token %}
</form>

osquickstart/templates/_default_sidebar.html
{% load sponsorship_tags %}
{% load thumbnail %}
{% load boxes_tags %}

{% sponsor_levels as levels %}

<h4>Sponsors</h4>

<div class="sponsor-list">
    {% box "sponsor-top" %}
    {% for level in levels %}
        {% if level.sponsors %}
            <h3 style="margin-top: 3em;">{{ level.name }}</h3>
            
            {% for sponsor in level.sponsors %}
                <div style="margin: 10px 0;">
                    <a href="{{ sponsor.external_url }}">
                        <img src="{% thumbnail sponsor.website_logo '100x60' %}" alt="{{ sponsor.name }}" />
                    </a>
                </div>
            {% endfor %}
        {% endif %}
    {% endfor %}
</div>

osquickstart/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load boxes_tags %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    {% box "homepage" %}
    &nbsp;
{% endblock %}

osquickstart/templates/proposals/_pending_proposal_row.html
{% load i18n %}

<tr>
    <td>
        <a href="{% url proposal_detail proposal.pk %}">{{ proposal.title }}</a>
    </td>
    
    <td>{{ proposal.kind.name }}</td>
    
    <td>
        {% if proposal.cancelled %}
            <span class="label label-important">{% trans 'Cancelled' %}</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">{% trans 'Accepted' %}</span>
                {% else %}
                    <span class="label">{% trans 'Submitted' %}</span>
                {% endif %}
            {% else %}
                <span class="label">{% trans 'Invited' %}</span>
            {% endif %}
        {% endif %}
    </td>
        
    <td>
        {% if not proposal.cancelled %}
            <div class="btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                {% trans 'Choose Response' %}
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url proposal_pending_join proposal.id %}">
			{% trans 'Accept invitation' %}</a></li>
                    <li><a href="{% url proposal_pending_decline proposal.id
		    %}">{% trans 'Decline invitation' %}</a></li>
                </ul>
            </div>
        {% endif %}
    </td>
</tr>

osquickstart/templates/proposals/_proposal_fields.html
{% load i18n %}

<dl class="dl-horizontal">
    <dt>{% trans "Submitted by" %}</dt>
    <dd>{{ proposal.speaker }}</dd>
    
    <dt>{% trans "Track" %}</dt>
    <dd>{{ proposal.track }}&nbsp;</dd>
    
    <dt>{% trans "Audience Level" %}</dt>
    <dd>{{ proposal.get_audience_level_display }}&nbsp;</dd>
    
    {% if proposal.additional_speakers.all %}
        <dt>{% trans "Additional Speakers" %}</dt>
        <dd>
            {% for speaker in proposal.additional_speakers.all %}
                <li>
                    {% if speaker.user %}
                        <strong>{{ speaker.name }}</strong> &lt;{{ speaker.email }}&gt;
                    {% else %}
                        {{ speaker.email }} ({% trans "Invitation Sent" %})
                    {% endif %}
                </li>
            {% endfor %}
        </dd>
    {% endif %}
    
    <dt>{% trans "Description" %}</dt>
    <dd>{{ proposal.description }}&nbsp;</dd>
    
    <dt>{% trans "Abstract" %}</dt>
    <dd>{{ proposal.abstract|safe }}&nbsp;</dd>
    
    <dt>{% trans "Notes" %}</dt>
    <dd>{{ proposal.additional_notes|safe }}&nbsp;</dd>
    
    <dt>{% trans "Speaker Bio" %}</dt>
    <dd>{{ proposal.speaker.biography|safe }}&nbsp;</dd>
    
    <dt>{% trans "Documents" %}</dt>
    <dd>
        {% if proposal.supporting_documents.exists %}
            <table class="table table-striped">
                {% for document in proposal.supporting_documents.all %}
                    <tr>
                        <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                        <td>
                        <form style="margin: 0;" method="post" action="{% url proposal_document_delete document.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-mini">delete</button>
                        </form>
                    </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            No supporting documents attached to this proposal.
        {% endif %}
    </dd>
</dl>

osquickstart/templates/proposals/_proposal_row.html
<tr>
    <td>
        <a href="{% url proposal_detail proposal.pk %}">{{ proposal.title }}</a>
    </td>
    
    <td>{{ proposal.kind.name }}</td>
    
    <td>
        {% if proposal.cancelled %}
            <span class="label label-important">Cancelled</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">Accepted</span>
                {% else %}
                    <span class="label">Submitted</span>
                {% endif %}
            {% else %}
                <span class="label">Associated</span>
            {% endif %}
        {% endif %}
    </td>
        
    <td>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user and proposal.can_edit %}
                <a href="{% url proposal_edit proposal.pk %}" class="btn btn-mini"><i class="icon-pencil"></i> Edit</a>
                <a href="{% url proposal_speaker_manage proposal.id %}" class="btn btn-mini"><i class="icon-user"></i> Manage Additional Speakers</a>
            {% endif %}
        {% endif %}
    </td>
</tr>

osquickstart/templates/proposals/base.html
{% extends "site_base_onecolumn.html" %}

osquickstart/templates/proposals/proposal_detail.html
{% extends "proposals/base.html" %}

{% load i18n %}
{% load account_tags %}
{% load bootstrap_tags %}

{% block head_title %}{{ proposal.title }}{% endblock %}

{% block body %}
    <div class="pull-right">
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user %}
                <a href="{% url proposal_edit proposal.pk %}" class="btn">
                    {% trans "Edit this proposal" %}
                </a>
                <a href="{% url proposal_cancel proposal.pk %}" class="btn">
                    {% trans "Cancel this proposal" %}
                </a>
            {% else %}
                <a href="{% url proposal_leave proposal.pk %}" class="btn">
                    {% trans "Remove me from this proposal" %}
                </a>
            {% endif %}
        {% else %}
            {% trans 'Cancelled' }
        {% endif %}
    </div>
    
    <h3>#{{ proposal.number }}: {{ proposal.title }} ({{ proposal.speaker }}, Track: {{ proposal.track }})</h3>
    
    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#proposal-detail" data-toggle="tab">{% trans "Proposal Details" %}</a></li>
            {% if request.user == proposal.speaker.user %}
                <li><a href="#proposal-documents" data-toggle="tab">{% trans "Supporting Documents" %}</a></li>
            {% endif %}
            {% if message_form %}
                <li><a href="#proposal-feedback" data-toggle="tab">{% trans "Reviewer Feedback" %} <span class="badge">{{ proposal.messages.all|length }}</span></a></li>
            {% endif %}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="proposal-detail">
                {% include "proposals/_proposal_fields.html" %}
            </div>
            {% if request.user == proposal.speaker.user %}
                <div class="tab-pane" id="proposal-documents">
                    <h3>{% trans 'Supporting Documents' %}</h3>
                    
                    {% if proposal.supporting_documents.exists %}
                        <table class="table table-striped">
                            {% for document in proposal.supporting_documents.all %}
                                <tr>
                                    <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                                    <td>
                                    <form style="margin: 0;" method="post" action="{% url proposal_document_delete document.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-mini">{% trans 'delete' %}</button>
                                    </form>
                                </td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <p>{% trans 'No supporting documents attached to this proposal.' %}</p>
                    {% endif %}
                    <a class="btn btn-small{% if proposal.cancelled %} btn-disabled{% endif %}" href="{% url proposal_document_create proposal.pk %}"><i class="icon-upload"></i> {% trans 'Add Document' %}</a>
                </div>
            {% endif %}
    
    {% if message_form %}
        <div class="tab-pane" id="proposal-feedback">
            
            <h3>{% trans 'Conversation with Reviewers' %}</h3>
            
            {% for message in proposal.messages.all %}
                <div class="review-box">
                    <div class="comment">{{ message.message|safe }}</div>
                    <div class="dateline"><b>{% user_display message.user %}</b> {{ message.submitted_at|timesince }} ago</div>
                </div>
                <div class="clear"></div>
            {% endfor %}
            
            <h3>{% trans 'Leave a Message' %}</h3>
            
            <p>{% trans 'You can leave a message for the reviewers here.' %}</p>
            
            <form action="" method="POST" accept-charset="utf-8">
                {% csrf_token %}
                <fieldset>
                    {{ message_form|as_bootstrap }}
                </fieldset>
                <div class="actions">
                    <button type="submit" name="message_submit" class="btn
		    primary">{% trans 'Submit' %}</button>
                </div>
            </form>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_script %}
    <script src="{{ STATIC_URL }}symposion/js/jquery.history.js"></script>
    <script type="text/javascript">
        $(function() {
            var History = window.History;
            
            $(window).bind("anchorchange", function() {
                $(".nav-tabs a[href='" + location.hash + "']").click();
            });
            
            $('#.nav-tabs a[data-toggle="tab"]').on('shown', function (e) {
                if (History.enabled) {
                    History.pushState(null, null, $(e.target).attr("href"));
                }
            });
        });
    </script>
{% endblock extra_script %}

osquickstart/templates/reviews/_result_notification_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} proposal.title {% templatetag closevariable %}</code> e.g. {{ proposals.0.title }}
    <li><code>{% templatetag openvariable %} proposal.kind {% templatetag closevariable %}</code> e.g. {{ proposals.0.kind }}
    <li><code>{% templatetag openvariable %} proposal.speaker {% templatetag closevariable %}</code> e.g. {{ proposals.0.speaker }}
</ul>

osquickstart/templates/reviews/_review_table.html
{% load i18n %}

<table class="table table-striped table-bordered table-reviews">
    <thead>
        <th>#</th>
        <th>{% trans "Speaker / Title" %}</th>
        <th>{% trans "Category" %}</th>
        <th><i class="icon-comment-alt"></i></th>
        <th>{% trans "+1" %}</th>
        <th>{% trans "+0" %}</th>
        <th>{% trans "-0" %}</th>
        <th>{% trans "-1" %}</th>
        <th><a href="#" class="tip" title="{% trans "Your Rating" %}"><i class="icon-user"></i></a></th>
    </thead>
    
    <tbody>
        {% for proposal in proposals %}
            <tr class="{{ proposal.user_vote_css }}">
                <td>{{ proposal.number }}</td>
                <td>
                    <a href="{% url review_detail proposal.pk %}">
                        <small><strong>{{ proposal.speaker }}</strong></small>
                        <br />
                        {{ proposal.title }}
                    </a>
                </td>
                <td>{{ proposal.track }}</td>
                <td>{{ proposal.comment_count }}</td>
                <td>{{ proposal.plus_one }}</td>
                <td>{{ proposal.plus_zero }}</td>
                <td>{{ proposal.minus_zero }}</td>
                <td>{{ proposal.minus_one }}</td>
                <td>{{ proposal.user_vote|default:"" }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

osquickstart/templates/reviews/access_not_permitted.html
{% extends "reviews/base.html" %}

{% block body %}
    <h1>Access Not Permitted</h1>
    
    <p>
        Sorry, you do not have permission to access this page. If you 
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

osquickstart/templates/reviews/base.html
{% extends "site_base.html" %}

{% load i18n %}
{% load sitetree %}

{% block extra_style %}
    <style type="text/css">
        div.dataTables_length label {
            float: left;
            text-align: left;
        }

        div.dataTables_length select {
            width: 75px;
        }

        div.dataTables_filter label {
            float: right;
        }

        div.dataTables_info {
            padding-top: 8px;
        }

        div.dataTables_paginate {
            float: right;
            margin: 0;
        }

        table.table {
            clear: both;
            margin-bottom: 6px !important;
            background-color: white;
        }

        table.table thead .sorting,
        table.table thead .sorting_asc,
        table.table thead .sorting_desc,
        table.table thead .sorting_asc_disabled,
        table.table thead .sorting_desc_disabled {
            cursor: pointer;
            *cursor: hand;
        }

        table.dataTable th:active {
            outline: none;
        }
    </style>
{% endblock %}

{% block body_class %}reviews{% endblock %}

{% block body_outer %}
    <div class="row">
        <div class="span2">
            {% block sidebar %}
                <ul class="nav nav-list well">
                    {% for section in review_sections %}
                        <li class="nav-header">
                            {{ section }}
                        </li>
                        <li>
                            <a href="{% url review_section section.section.slug %}">
                                {% trans "All Reviews" %}
                            </a>
                        </li>
                        {% comment %}
                        <li>
                            <a href="{% url review_section_assignments section.section.slug %}">
                                {% trans "Your Assignments" %}
                            </a>
                        </li>
                        {% endcomment %}
                        <li>
                            <a href="{% url review_status section.section.slug %}">
                                {% trans "Voting Status" %}
                            </a>
                        </li>
                        {% if request.user.is_staff %}
                            <li>
                                <a href="{% url result_notification section.section.slug 'accepted' %}">Result Notification</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endblock %}
        </div>
        <div class="span10">
            {% block body %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <script src="{{ STATIC_URL }}datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}tabletools/js/TableTools.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}datatables/js/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $(".tip").tooltip();
            $("table.table-reviews").dataTable({
                "sDom": "<'row'<'span3'l><'span3'T><'span4'f>r>t<'row'<'span3'i><'span5'p>>",
                "sPaginationType": "bootstrap",
                "bStateSave": true,
                "oTableTools": {
                    "aButtons": [
                        "copy",
                        "csv",
                        "print"
                    ],
                    "sSwfPath": "{{ STATIC_URL }}tabletools/swf/copy_csv_xls.swf"
                }
            });
        });
    </script>
{% endblock %}

osquickstart/templates/reviews/result_notification.html
{% extends "reviews/base.html" %}

{% load i18n %}

{% block extra_style %}
    <style type="text/css">
        .table-striped tbody tr.selected td {
            background-color: #F7F4E6;
        }
    </style>
{% endblock %}

{% block body %}
    
    <ul class="nav nav-pills">
        <li{% if status == 'accepted' %} class="active"{% endif %}><a href="{% url result_notification section_slug 'accepted' %}">accepted</a>
        <li{% if status == 'rejected' %} class="active"{% endif %}><a href="{% url result_notification section_slug 'rejected' %}">rejected</a>
        <li{% if status == 'standby' %} class="active"{% endif %}><a href="{% url result_notification section_slug 'standby' %}">standby</a>
    </ul>
    
    <h1>Result Notification</h1>
    
    <form method="post" action="{% url result_notification_prepare section_slug status %}">
        
        {% csrf_token %}
        
        <p>
            Select one or more proposals (<span class="action-counter">0</span> currently selected)
            <br/>
            then pick an email template
            <select name="notification_template">
                <option value="">[blank]</option>
                {% for template in notification_templates %}
                    <option value="{{ template.pk }}">{{ template.label }}</option>
                {% endfor %}
            </select>
            <br/>
            <button id="next-button" type="submit" class="btn btn-primary" disabled>Next <i class="icon icon-chevron-right"></i></button>
        </p>
        
        <table class="table table-striped table-bordered">
            <thead>
                <th><input type="checkbox" id="action-toggle"></th>
                <th>#</th>
                <th>{% trans "Speaker / Title" %}</th>
                <th>{% trans "Category" %}</th>
                <th>{% trans "Status" %}</th>
                <th>{% trans "Notified?" %}</th>
            </thead>
            
            <tbody>
                {% for proposal in proposals %}
                    <tr>
                        <td><input class="action-select" type="checkbox" name="_selected_action" value="{{ proposal.pk }}"></td>
                        <td>{{ proposal.number }}</td>
                        <td>
                            <a href="{% url review_detail proposal.pk %}">
                                <small><strong>{{ proposal.speaker }}</strong></small>
                                <br />
                                {{ proposal.title }}
                            </a>
                        </td>
                        <td>{{ proposal.track }}</td>
                        <td>
                            {% with proposal.result.status as status %}
                                <div class="{{ status }}">
                                    {% if status != "undecided" %}
                                        <span>{{ status }}</span>
                                    {% endif %}
                                </div>
                            {% endwith %}
                        </td>
                        <td>
                            {% if proposal.notifications.exists %}yes{% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        (function($) {
            $.fn.actions = function(opts) {
                var options = $.extend({}, $.fn.actions.defaults, opts);
                var actionCheckboxes = $(this);
                checker = function(checked) {
                    $(actionCheckboxes).prop("checked", checked)
                        .parent().parent().toggleClass(options.selectedClass, checked);
                }
                updateCounter = function() {
                    var sel = $(actionCheckboxes).filter(":checked").length;
                    $(options.counterContainer).html(sel);
                    $(options.allToggle).prop("checked", function() {
                        if (sel == actionCheckboxes.length) {
                            value = true;
                        } else {
                            value = false;
                        }
                        return value;
                    });
                    if (sel == 0) {
                        $("#next-button").prop("disabled", true);
                    } else {
                        $("#next-button").prop("disabled", false);
                    }
                }
                // Check state of checkboxes and reinit state if needed
                $(this).filter(":checked").each(function(i) {
                    $(this).parent().parent().toggleClass(options.selectedClass);
                    updateCounter();
                });
                $(options.allToggle).click(function() {
                    checker($(this).prop("checked"));
                    updateCounter();
                });
                lastChecked = null;
                $(actionCheckboxes).click(function(event) {
                    if (!event) { var event = window.event; }
                    var target = event.target ? event.target : event.srcElement;
                    if (lastChecked && $.data(lastChecked) != $.data(target) && event.shiftKey == true) {
                        var inrange = false;
                        $(lastChecked).prop("checked", target.checked)
                            .parent().parent().toggleClass(options.selectedClass, target.checked);
                        $(actionCheckboxes).each(function() {
                            if ($.data(this) == $.data(lastChecked) || $.data(this) == $.data(target)) {
                                inrange = (inrange) ? false : true;
                            }
                            if (inrange) {
                                $(this).prop("checked", target.checked)
                                    .parent().parent().toggleClass(options.selectedClass, target.checked);
                            }
                        });
                    }
                    $(target).parent().parent().toggleClass(options.selectedClass, target.checked);
                    lastChecked = target;
                    updateCounter();
                });
            }
            /* Setup plugin defaults */
            $.fn.actions.defaults = {
                counterContainer: "span.action-counter",
                allToggle: "#action-toggle",
                selectedClass: "selected"
            }
        })($);
        $(function() {
            $("tr input.action-select").actions();
        });
    </script>
{% endblock %}

osquickstart/templates/reviews/review_review.html
{% extends "site_base.html" %}

{% load markitup_tags %}
{% load uni_form_tags %}

{% block body_class %}review{% endblock %}

{% block body %}
    <h1>Proposal Review</h1>
    
    <div class="proposal">
        <h2>{{ proposal.title }}</h2>
        
        <p>
            {% if proposal.cancelled %}
                Cancelled
            {% endif %}
        </p>
        
        <div>
            {{ proposal.description }}
        </div>
        
        <p><b>Type</b>: {{ proposal.get_session_type_display }}</p>
        
        <h3>Abstract</h3>
        <div class="abstract">
            {{ proposal.abstract_html|safe }}
        </div>
        
        <p><b>Audience level</b>: {{ proposal.get_audience_level_display }}</p>
        
        <p><b>Submitting speaker</b>: {{ proposal.speaker }}</p> {# @@@ bio? #}
        
        {% if proposal.additional_speakers.all %}
            <p><b>Additional speakers</b>:</p>
            <ul>
            {% for speaker in proposal.additional_speakers.all %}
                {% if speaker.user %}
                    <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
                {% else %}
                    <li>{{ speaker.email }} &mdash; pending invitation</li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
        
        <h3>Additional Notes (private from submitter)</h3>
        <div class="additional_notes">
            {{ proposal.additional_notes }}
        </div>
    </div>
    
    {% markitup_media %}

    <h2>Review</h2>
    
    <form method="POST" action="{% url review_review proposal.pk %}" class="uniForm">
        {% csrf_token %}
        <fieldset class="inlineLabels">
            {{ review_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" value="Submit" />
            </div>
        </fieldset>
    </form>
    
    <h2>Comment</h2>
    
    <form method="POST" action="{% url review_comment proposal.pk %}" class="uniForm">
        {% csrf_token %}
        <fieldset>
            {{ comment_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" value="Submit" />
            </div>
        </fieldset>
    </form>
    
{% endblock %}